### ISSUE TITLE
Does not seem to work (windows 10, Ryujinx 1.1.811)

### ISSUE THREAD

**Issue by joric** [IamSanjid/RMB#5]
Does not start with 1.1.811 and window title "Ryujinx". Maybe window title has changed to include full game and version? Mine says `Ryujinx 1.1.811 - The Legend of Zelda: Tears of the Kingdom v1.0.0 (0100F2C0115B6000) (64-bit)`. App doesn't bind to this title either. When I change title in the app to empty string, app starts but doesn't send keys to emulator. Also confirmed on Reddit https://www.reddit.com/r/Ryujinx/comments/thqtww/simple_utility_to_map_your_mouse_to/ Also I play on the second display, maybe it's the matter (doesn't seem to change if I duplicate the display though).

**Comment by IamSanjid** [comment]
Run the app in Administrator Mode, Windows 11 seems want application to run in Administrator mode in order to perfom Window Management actions. The app tries to send virtual key presses to Ryujinx that's why it needs the Window management action permission.

**Comment by joric** [comment]
I confirm Administrator mode works and works great. Closing.
